[package]
name = "sentinel-events"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Raw event transformation pipeline"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
byteorder = "1"
sentinel-core = { path = "../sentinel-core" }
sentinel-common = { path = "../sentinel-common" }
