use crate::MatchReport;

/// Markdown report generator
pub struct MarkdownReport;

impl MarkdownReport {
    /// Generate a Markdown report from match data
    pub fn generate(report: &MatchReport) -> String {
        let mut md = String::new();

        // Header
        md.push_str("# Sentinel AI Analysis Report\n\n");

        // Metadata
        md.push_str("## Match Information\n\n");
        md.push_str(&format!("- **Map:** {}\n", report.metadata.map_name));
        md.push_str(&format!("- **Server:** {}\n", report.metadata.server_name));
        md.push_str(&format!("- **Rounds:** {}\n", report.metadata.total_rounds));
        md.push_str(&format!(
            "- **Duration:** {:.1}s\n",
            report.metadata.duration_seconds
        ));
        md.push_str(&format!("- **Tick Rate:** {}\n", report.metadata.tick_rate));
        md.push_str(&format!("- **Demo:** `{}`\n\n", report.metadata.demo_path));

        // Overall score
        md.push_str("## Overall Analysis\n\n");
        md.push_str(&format!(
            "**Anomaly Score:** {:.2}/1.0\n\n",
            report.overall_anomaly
        ));

        let grade = Self::score_grade(report.overall_anomaly);
        md.push_str(&format!("**Assessment:** {}\n\n", grade));

        // Player reports
        md.push_str("## Player Analysis\n\n");

        for player in &report.players {
            md.push_str(&format!("### {} ({})\n\n", player.name, player.steam_id));
            md.push_str(&format!("- **Team:** {}\n", player.team));
            md.push_str(&format!(
                "- **Overall Score:** {:.2}\n",
                player.scores.overall
            ));

            // Category scores
            md.push_str("- **Category Scores:**\n");
            for (category, score) in &player.scores.categories {
                let bar = Self::score_bar(*score);
                md.push_str(&format!("  - {}: {:.2} {}\n", category, score, bar));
            }

            // Evidence
            if !player.evidence.is_empty() {
                md.push_str(&format!(
                    "\n**Evidence:** {} items\n\n",
                    player.evidence.len()
                ));
                md.push_str("| Tick | Feature | Score | Reason |\n");
                md.push_str("|------|---------|-------|--------|\n");

                for ev in &player.evidence {
                    md.push_str(&format!(
                        "| {} | {} | {:.2} | {} |\n",
                        ev.tick.0, ev.feature, ev.score, ev.reason
                    ));
                }
            } else {
                md.push_str("\n*No anomalous behavior detected.*\n");
            }

            md.push_str("\n---\n\n");
        }

        // Footer
        md.push_str(&format!(
            "*Report generated by Sentinel AI v{}*\n",
            report.version
        ));

        md
    }

    /// Get a grade based on anomaly score
    fn score_grade(score: f64) -> &'static str {
        if score < 0.2 {
            "Clean - No suspicious behavior"
        } else if score < 0.4 {
            "Low suspicion - Minor anomalies"
        } else if score < 0.6 {
            "Moderate suspicion - Notable anomalies"
        } else if score < 0.8 {
            "High suspicion - Significant anomalies"
        } else {
            "Critical - Strong indicators of unfair play"
        }
    }

    /// Generate a text-based score bar
    fn score_bar(score: f64) -> String {
        let filled = (score * 10.0) as usize;
        let empty = 10 - filled;
        format!("[{}{}]", "█".repeat(filled), "░".repeat(empty))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_score_grade() {
        assert_eq!(
            MarkdownReport::score_grade(0.1),
            "Clean - No suspicious behavior"
        );
        assert_eq!(
            MarkdownReport::score_grade(0.5),
            "Moderate suspicion - Notable anomalies"
        );
        assert_eq!(
            MarkdownReport::score_grade(0.9),
            "Critical - Strong indicators of unfair play"
        );
    }
}
